services:

  django-web:
    restart: always
    hostname: ${HOSTNAME}
    image: visibleaccess/web-container-django-web:v4
    user: ubuntu
    stdin_open: true
    tty: true
    container_name: django-docker
    ports:
      - "8000:8000"

    volumes:
      - ./static:/app/staticfiles:rw
      - /efs:/efs

    env_file:
      - ./env/env.prod
      - ./env/env.config
      - ./env/env.secret


    environment:
      SITE_URL: ${SITE_URL}


  frontend-proxy:
    restart: always
    image: nginx:latest
    stdin_open: true
    tty: true
    ports:
      - "80:80"
      - "443:443"

    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./static:/static:ro
    depends_on:
      - django-web

